HomeShare/Controllers/UserLoginController.cs
using HomeShare.DAL;
using HomeShare.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace HomeShare.Controllers
{
    public class UserLoginController : Controller
    {
        public object FormAuthentication { get; private set; }

        // GET: UserLogin
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Index(LoginModel lm)
        {
            string mainconn = ConfigurationManager.ConnectionStrings["cnstr"].ConnectionString;
            SqlConnection sqlconn = new SqlConnection(mainconn);
            SqlCommand sqlcomm = new SqlCommand("[dbo].[Membre]");
            sqlconn.Open();
            sqlcomm.Connection = sqlconn;
            //sqlcomm.CommandType = CommandType.StoredProcedure;
            sqlcomm.Parameters.AddWithValue("@Email", lm.UserEmail);
            sqlcomm.Parameters.AddWithValue("@Password", lm.Password);
            SqlDataReader sdr = sqlcomm.ExecuteReader();

            if (sdr.Read())
            {
                FormsAuthentication.SetAuthCookie(lm.UserEmail, true);
                Session["username"] = lm.UserEmail.ToString();
                return RedirectToAction("Welcome");
            }

            else
            {
                ViewData["message"] = "Login details are not correct!Try it again!";

            }

            sqlconn.Close();
            return View();
        }
        public ActionResult Welcome()
        {
            return View();
        }


    }
}

HomeShare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Home Share</title>
    @Styles.Render("~/assets/css")
    @Styles.Render("~/assets/owl-carousel/css")
    @Styles.Render("~/assets/slitslider/css")

    @Scripts.Render("~/assets/js")
    @Scripts.Render("~/assets/owl-carousel/js")
    @Scripts.Render("~/assets/slitslider/js")
    
    <script src="http://code.jquery.com/jquery-1.9.1.min.js" type="text/javascript"></script>
</head>
<body>


    <!-- Header Starts -->
    <div class="navbar-wrapper">

        <div class="navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">


                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>


                <!-- Nav Starts -->
                <div class="navbar-collapse  collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active">@Html.ActionLink("HOME", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("PROPOSE", "Propose", "Home")</li>
                        <li>@Html.ActionLink("HOSTS", "About", "Home")</li>
                        <li>@Html.ActionLink("HOME FOR SHARE", "HomeForShare", "Home")</li>
                        <li>@Html.ActionLink("CONTACT US", "Contact", "Home")</li>
                    </ul>
                </div>
                <!-- #Nav Ends -->

            </div>
        </div>

    </div>
    <!-- #Header Starts -->





    <div class="container">

        <!-- Header Starts -->
        <div class="header">
            <img src="../images/logo.png" alt="Realestate">


            <ul class="pull-right">
                <li>
                    @Html.ActionLink("Exchange", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

                </li>
                <li>
                    @Html.ActionLink("Visit", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </li>
                <li>
                    @Html.ActionLink("Login", "Index", "UserLogin", new { area = "" }, new { @class = "navbar-brand" })
                </li>
            </ul>
        </div>
        <!-- #Header Starts -->
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="footer">

                <div class="container">



                    <div class="row">
                        <div class="col-lg-3 col-sm-3">
                            <h4>Information</h4>
                            <ul class="row">
                                <li class="col-lg-12 col-sm-12 col-xs-3">
                                    @Html.ActionLink("About", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                                </li>
                                <li class="col-lg-12 col-sm-12 col-xs-3">
                                    @Html.ActionLink("Team", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                                </li>
                                <li class="col-lg-12 col-sm-12 col-xs-3">
                                    @Html.ActionLink("Blog", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                                </li>
                                <li class="col-lg-12 col-sm-12 col-xs-3">
                                    @Html.ActionLink("Contact", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                                </li>
                            </ul>
                        </div>

                        <div class="col-lg-3 col-sm-3">
                            <h4>Newsletter</h4>
                            <p>Get notified about the latest House to share in our region.</p>
                            <form class="form-inline" role="form">
                                <input type="text" placeholder="Enter Your email address" class="form-control">
                                <button class="btn btn-success" type="button">Notify Me!</button>
                            </form>
                        </div>

                        <div class="col-lg-3 col-sm-3">
                            <h4>Follow us</h4>
                            <a href="#"><img src="../images/facebook.png" alt="facebook"></a>
                            <a href="#"><img src="../images/twitter.png" alt="twitter"></a>
                            <a href="#"><img src="../images/linkedin.png" alt="linkedin"></a>
                            <a href="#"><img src="../images/instagram.png" alt="instagram"></a>
                        </div>

                        <div class="col-lg-3 col-sm-3">
                            <h4>Contact us</h4>
                            <p>
                                <b>Bootstrap Realestate Inc.</b><br>
                                <span class="glyphicon glyphicon-map-marker"></span> 8290 Walk Street, Belgium <br>
                                <span class="glyphicon glyphicon-envelope"></span> hello@bootstrapreal.com<br>
                                <span class="glyphicon glyphicon-earphone"></span> (+32) 456-7890
                            </p>
                        </div>
                    </div>
                    <p>&copy; @DateTime.Now.Year - Home Share</p>

                </div>
            </div>




            <!-- Modal -->
            <div id="loginpop" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="row">
                            <div class="col-sm-6 login">
                                <h4>Login</h4>
                                <form class="" role="form">
                                    <div class="form-group">
                                        <label class="sr-only" for="exampleInputEmail2">Email address</label>
                                        <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter email">
                                    </div>
                                    <div class="form-group">
                                        <label class="sr-only" for="exampleInputPassword2">Password</label>
                                        <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password">
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"> Remember me
                                        </label>
                                    </div>
                                    <button type="submit" class="btn btn-success">Sign in</button>
                                </form>
                            </div>
                            <div class="col-sm-6">
                                <h4>New User Sign Up</h4>
                                <p>Join today and get updated with all the Home Share happening around.</p>
                                <button type="submit" class="btn btn-info"> @Html.ActionLink("Register", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</button>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <!-- /.modal -->




        </footer>
    </div>

    @Scripts.Render("~/assets/js")
    @Scripts.Render("~/assets/owl-carousel/js")
    @Scripts.Render("~/assets/slitslider/js")
    @RenderSection("scripts", required: false)
</body>
</html>