HomeShare/Controllers/UserLoginController.cs
using HomeShare.DAL;
using HomeShare.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace HomeShare.Controllers
{
    public class UserLoginController : Controller
    {
        public object FormAuthentication { get; private set; }

        // GET: UserLogin
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Index(LoginModel lm)
        {
            string mainconn = ConfigurationManager.ConnectionStrings["cnstr"].ConnectionString;
            SqlConnection sqlconn = new SqlConnection(mainconn);
            SqlCommand sqlcomm = new SqlCommand("[dbo].[Membre]");
            sqlconn.Open();
            sqlcomm.Connection = sqlconn;
            //sqlcomm.CommandType = CommandType.StoredProcedure;
            sqlcomm.Parameters.AddWithValue("@Email", lm.UserEmail);
            sqlcomm.Parameters.AddWithValue("@Password", lm.Password);
            SqlDataReader sdr = sqlcomm.ExecuteReader();

            if (sdr.Read())
            {
                FormsAuthentication.SetAuthCookie(lm.UserEmail, true);
                Session["username"] = lm.UserEmail.ToString();
                return RedirectToAction("Welcome");
            }

            else
            {
                ViewData["message"] = "Login details are not correct!Try it again!";

            }

            sqlconn.Close();
            return View();
        }
        public ActionResult Welcome()
        {
            return View();
        }


    }
}

HomeShare/Controllers/ValidateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeShare.Controllers
{
    public class ValidateController : Controller
    {
        // GET: Validate
        public ActionResult Index()
        {
            return View();
        }

        // GET: Validate/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Validate/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Validate/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Validate/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Validate/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Validate/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Validate/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HomeShare/Views/UserLogin/Index.cshtml
@model HomeShare.Models.LoginModel

@{
    ViewBag.Title = "Index";
}




@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Login</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
        <h2>@Html.ViewData["Message"]</h2>
    </div>
}
<h2> @Html.ActionLink("Or Sign Up ", "Create","Validate")</h2>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeShare/Views/UserLogin/Welcome.cshtml
@{
    ViewBag.Title = "Welcome";
}

@if (Session["username"] != null)
{
    <h4>welcome @Session["username"].ToString()</h4>
}

else
{
    Response.Redirect("Index");
}


@section Scripts {
    @Scripts.Render("~/bundles/plugin")
}

<script type="text/javascript">
    function preventBack() {
        window.history.forward();
    }
    setTimeout("preventBack()", 0);
    window.onunload = function () {
        null;
    }
</script>